drop view BSSV_CITY;

create view BSSV_CITY
(ID,NAME,CODE,STATE_REGION,LATITUDE,LONGITUDE,COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME)
as
select
	a.CIT_N_CITY_ID,a.CIT_S_NAME,a.CIT_S_CODE,a.CIT_S_STATE_REGION,
	a.CIT_D_LOC_LAT,a.CIT_D_LOC_LNG,a.CON_N_COUNTRY_ID,
	b.CON_S_CODE,b.CON_S_NAME
	from BSST_CIT_CITY a
	left join BSST_CON_COUNTRY b on a.CON_N_COUNTRY_ID=b.CON_N_COUNTRY_ID;
	
