drop view BSSV_COMPANY;

create view BSSV_COMPANY
(ID,CODE,NAME,ADDRESS,ZIP,CITY_ID,CITY,
FISCAL_CODE,VAT_CODE,HEAD_DEPT_ID
)
as
select
	a.COM_N_COMPANY_ID,a.COM_S_CODE,a.COM_S_NAME,a.COM_S_ADDRESS,a.COM_S_ZIP,
	a.CIT_N_CITY_ID,c.CIT_S_NAME,a.COM_S_FISCAL_CODE,a.COM_S_VAT_CODE,b.CDE_N_DEPT_ID
	from BSST_COM_COMPANY a
	join BSST_CDE_COMPANY_DEPT b on a.COM_N_COMPANY_ID=b.COM_N_COMPANY_ID
	left join BSST_CIT_CITY c on a.CIT_N_CITY_ID=b.CIT_N_CITY_ID
	where b.CDE_N_PARENT_DEPT_ID is NULL;
	
	

