drop view BSSV_PRODUCT_CATEGORY;

create view BSSV_PRODUCT_CATEGORY
(ID,NAME,VAT,METRIC_ID,METRIC_NAME,DESCRIPTION)
as
select
	a.PCA_N_PRODUCT_CATEGORY_ID,a.PCA_S_NAME,a.PCA_N_VAT,a.MET_N_METRIC_ID,b.MET_S_NAME,a.PCA_S_DESC
	from 
	BSST_PCA_PRODUCT_CATEGORY a
	join BSST_MET_METRIC b on a.MET_N_METRIC_ID=b.MET_N_METRIC_ID;
	
