drop view BSSV_PRODUCT_CATEGORY;

create view BSSV_PRODUCT_CATEGORY
(ID,NAME,VAT,METRIC_ID,METRIC_NAME,DESCRIPTION)
as
select
	a.PCA_N_PRODUCT_CATEGORY_ID,a.PCA_S_NAME,a.PCA_N_VAT,a.MET_N_METRIC_ID,b.MET_S_NAME,a.PCA_S_DESC
	from 
	BSST_PCA_PRODUCT_CATEGORY a
	join BSST_MET_METRIC b on a.MET_N_METRIC_ID=b.MET_N_METRIC_ID;
	

drop view BSSV_PRODUCT;

create view BSSV_PRODUCT
(ID,NAME,DESCRIPTION,CODE,CATEGORY_ID,CATEGORY_NAME,METRIC_ID,METRIC_NAME,VAT,TYPE_ID,TYPE_NAME,
PARENT_ID,PARENT_NAME,PRODUCER_ID,PRODUCER_CODE,PRODUCER_NAME)
as
select
	a.PRO_N_PRODUCT_ID,a.PRO_S_NAME,a.PRO_S_DESC,a.PRO_S_CODE,
	b.PCA_N_PRODUCT_CATEGORY_ID,b.PCA_S_NAME,
	c.MET_N_METRIC_ID,c.MET_S_NAME,
	b.PCA_N_VAT,
	d.PTY_N_PRODUCT_TYPE_ID,d.PTY_S_NAME,
	e.PRO_N_PRODUCT_ID,e.PRO_S_NAME,
	f.COM_N_COMPANY_ID,f.COM_S_CODE,f.COM_S_NAME
	from 
	BSST_PRO_PRODUCT a
	join BSST_PCA_PRODUCT_CATEGORY b on a.PCA_N_PRODUCT_CATEGORY_ID=b.PCA_N_PRODUCT_CATEGORY_ID
	join BSST_MET_METRIC c on c.MET_N_METRIC_ID=b.MET_N_METRIC_ID
	join BSST_PTY_PRODUCT_TYPE d on d.PTY_N_PRODUCT_TYPE_ID=a.PTY_N_PRODUCT_TYPE_ID
	left join BSST_PRO_PRODUCT e on a.PRO_N_PRODUCT_PARENT_ID=e.PRO_N_PRODUCT_ID
	left join BSST_COM_COMPANY f on a.PRO_N_PRODUCER_ID=f.COM_N_COMPANY_ID;
	