drop view BSSV_PERSON;

create view BSSV_PERSON
(ID,CODE,FIRST_NAME,SECOND_NAME,GENDER,ADDRESS,ZIP,
CITY_ID,CITY,FISCAL_CODE,BIRTH_DAY,BIRTH_CITY_ID,BIRTH_CITY)
as
select
	a.PER_N_PERSON_ID, a.PER_S_CODE, a.PER_S_FIRST_NAME, a.PER_S_SECOND_NAME, a.PER_C_GENDER,
	a.PER_S_ADDRESS, a.PER_S_ZIP,a.CIT_N_CITY_ID,b.CIT_S_NAME,a.PER_S_FISCAL_CODE, a.PER_D_BIRTH_DAY,
	a.CIT_N_BIRTH_CITY_ID,c.CIT_S_NAME
	from BSST_PER_PERSON a
	left join BSST_CIT_CITY b on a.CIT_N_CITY_ID=b.CIT_N_CITY_ID
	left join BSST_CIT_CITY c on a.CIT_N_BIRTH_CITY_ID=c.CIT_N_CITY_ID;
	
	
	

