delete from BSST_PRC_PRICE_COMPONENT;
delete from BSST_PRT_PRICE_TYPE;		

ALTER TABLE BSST_PRT_PRICE_TYPE AUTO_INCREMENT= 1;

INSERT INTO BSST_PRT_PRICE_TYPE(PRT_S_CODE,PRT_S_NAME,PRT_S_DESC)
	VALUES ('NRC','No Recurring Charge','No Recurring Charge');
INSERT INTO BSST_PRT_PRICE_TYPE(PRT_S_CODE,PRT_S_NAME,PRT_S_DESC)
	VALUES ('RC','Recurring Charge','Recurring Charge');
INSERT INTO BSST_PRT_PRICE_TYPE(PRT_S_CODE,PRT_S_NAME,PRT_S_DESC)
	VALUES ('USG','Usage','Usage');
	
ALTER TABLE BSST_PRC_PRICE_COMPONENT AUTO_INCREMENT= 1;

INSERT INTO BSST_PRC_PRICE_COMPONENT(PRC_S_CODE,PRC_S_NAME,PRC_S_DESC,PRT_N_PRICE_TYPE_ID)
	VALUES ('NRC_UT','Una Tantum','Una Tantum',(select PRT_N_PRICE_TYPE_ID from BSST_PRT_PRICE_TYPE where PRT_S_CODE='NRC'));
INSERT INTO BSST_PRC_PRICE_COMPONENT(PRC_S_CODE,PRC_S_NAME,PRC_S_DESC,PRT_N_PRICE_TYPE_ID)
	VALUES ('NRC_OFC','One-off Charge','One-off Charge',(select PRT_N_PRICE_TYPE_ID from BSST_PRT_PRICE_TYPE where PRT_S_CODE='NRC'));
INSERT INTO BSST_PRC_PRICE_COMPONENT(PRC_S_CODE,PRC_S_NAME,PRC_S_DESC,PRT_N_PRICE_TYPE_ID)
	VALUES ('USG_QXP','Quantity x PU','Quantity x Unit Price',(select PRT_N_PRICE_TYPE_ID from BSST_PRT_PRICE_TYPE where PRT_S_CODE='USG'));

