CREATE TABLE BSST_SER_SERVER (
	SER_N_SERVER_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SER_S_NODE_ID			VARCHAR(20) NOT NULL,
	SER_S_IP				VARCHAR(30),				
	SER_S_MACHINE			VARCHAR(50),
	SER_D_START_DATE		DATETIME,
	SER_D_STOP_DATE			DATETIME,
	SER_S_STATUS			VARCHAR(20) NOT NULL DEFAULT 'Stopped',
	UNIQUE(SER_S_NODE_ID),
	PRIMARY KEY(SER_N_SERVER_ID),
	CONSTRAINT BSST_SER_SERVER_CK1 CHECK(SER_S_STATUS IN ('Stopped','Pause','Running'))
);


CREATE TABLE BSST_SEC_SERVER_COMMAND(
	SEC_N_SERVER_COMMAND_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SEC_S_COMMAND 				VARCHAR(200) NOT NULL,
	SER_N_SERVER_ID 			INTEGER UNSIGNED NOT NULL,
	SEC_D_REQUESTED_EXEC_DATE 	DATETIME NOT NULL,
	SEC_D_EXECUTION_DATE 		DATETIME,
	SEC_S_STATUS				VARCHAR(20) NOT NULL DEFAULT 'Pending',
	SEC_S_RESULT 				VARCHAR(20),
	PRIMARY KEY(SEC_N_SERVER_COMMAND_ID),
	CONSTRAINT BSST_SEC_SERVER_COMMAND_FK1 FOREIGN KEY(SER_N_SERVER_ID) 
			REFERENCES BSST_SER_SERVER(SER_N_SERVER_ID),
	CONSTRAINT BSST_SEC_SERVER_COMMAND_CK1 CHECK(SEC_S_STATUS IN ('Pending','Executed','Running'))		
);

CREATE TABLE BSST_SEQ_SERVER_QUEUE(
	SEQ_N_QUEUE_ITEM_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	OBJ_N_OBJECT_ID 			INTEGER UNSIGNED NOT NULL,
	SEQ_N_OBJ_INST_ID			INTEGER UNSIGNED NOT NULL,
	SER_N_SERVER_ID 			INTEGER UNSIGNED,
	SEQ_D_REQUESTED_EXEC_DATE 	DATETIME NOT NULL,
	SEQ_D_START_EXEC_DATE 		DATETIME,
	SEQ_D_END_EXEC_DATE 		DATETIME,
	SEQ_S_STATUS				VARCHAR(20) NOT NULL DEFAULT 'Pending',
	SEQ_S_RESULT 				VARCHAR(20),
	PRIMARY KEY(SEQ_N_QUEUE_ITEM_ID),
	CONSTRAINT BSST_SEQ_SERVER_QUEUE_FK1 FOREIGN KEY(SER_N_SERVER_ID) 
			REFERENCES BSST_SER_SERVER(SER_N_SERVER_ID),
	CONSTRAINT BSST_SEQ_SERVER_QUEUE_FK2 FOREIGN KEY(OBJ_N_OBJECT_ID) 
			REFERENCES BSST_OBJ_OBJECT(OBJ_N_OBJECT_ID),
	CONSTRAINT BSST_SEQ_SERVER_QUEUE_CK1 CHECK(SEQ_S_STATUS IN ('Pending','Executed','Running'))		
);
