drop view BSSV_METRIC_SCALE;

create view BSSV_METRIC_SCALE
(ID,NAME,METRIC_ID,METRIC_NAME,SIMBOL,SCALE)
as
select
	a.MES_N_METRIC_SCALE_ID,a.MES_S_NAME,a.MET_N_METRIC_ID,b.MET_S_NAME,a.MES_S_SIMBOL,a.MES_N_SCALE
	from BSST_MES_METRIC_SCALE a
	join BSST_MET_METRIC b on a.MET_N_METRIC_ID=b.MET_N_METRIC_ID;
	
