drop view BSSV_PRICE_COMPONENT;

create view BSSV_PRICE_COMPONENT
(ID,CODE,NAME,DESCRIPTION,PERIOD_METRIC_ID,PERIOD_METRIC_NAME,TYPE_ID,TYPE_CODE,TYPE_NAME)
as
select
	a.PRC_N_PRICE_COMPONENT_ID,a.PRC_S_CODE,a.PRC_S_NAME,a.PRC_S_DESC,b.MET_N_METRIC_ID,b.MET_S_NAME,
	c.PRT_N_PRICE_TYPE_ID,c.PRT_S_CODE,c.PRT_S_NAME
	from BSST_PRC_PRICE_COMPONENT a
	left join BSST_MET_METRIC b on a.PRI_N_PERIOD_METRIC_ID=b.MET_N_METRIC_ID
	join BSST_PRT_PRICE_TYPE c on a.PRT_N_PRICE_TYPE_ID=c.PRT_N_PRICE_TYPE_ID;
	
