drop view BSSV_ATTRIBUTE;

create view BSSV_ATTRIBUTE
(ID,NAME,TYPE_ID,TYPE,OBJ_ID,OBJECT,ENTITY)
as
select
	a.ATT_N_ATTRIBUTE_ID,a.ATT_S_NAME,
	b.ATY_N_ATTR_TYPE_ID,b.ATY_S_NAME,
	c.OBJ_N_OBJECT_ID,c.OBJ_S_NAME,c.OBJ_S_ENTITY_NAME
	from BSST_ATT_ATTRIBUTE a
	join BSST_ATY_ATTR_TYPE b on a.ATY_N_ATTR_TYPE_ID=b.ATY_N_ATTR_TYPE_ID
	join BSST_OBJ_OBJECT c on c.OBJ_N_OBJECT_ID=a.OBJ_N_OBJECT_ID;
	
drop view BSSV_ATTRIBUTE_VALUE;

create view BSSV_ATTRIBUTE_VALUE
(ID,NAME,TYPE_ID,TYPE,OBJ_ID,OBJECT,ENTITY,OBJINST_ID,VALUE)
as
select
	a.ATT_N_ATTRIBUTE_ID,a.ATT_S_NAME,
	b.ATY_N_ATTR_TYPE_ID,b.ATY_S_NAME,
	c.OBJ_N_OBJECT_ID,c.OBJ_S_NAME,c.OBJ_S_ENTITY_NAME,
	d.ATV_N_OBJ_INST_ID,d.ATV_S_VALUE
	from BSST_ATT_ATTRIBUTE a
	join BSST_ATY_ATTR_TYPE b on a.ATY_N_ATTR_TYPE_ID=b.ATY_N_ATTR_TYPE_ID
	join BSST_OBJ_OBJECT c on c.OBJ_N_OBJECT_ID=a.OBJ_N_OBJECT_ID
	join BSST_ATV_ATTR_VALUE d on a.ATT_N_ATTRIBUTE_ID=d.ATT_N_ATTRIBUTE_ID;
