drop view BSSV_TICKET;

create view BSSV_TICKET
(ID,TEXT,CREATION_DATE,UPDATE_DATE,
STATUS_ID,STATUS_NAME,
USER_ID,USER_NAME,
CATEGORY_ID,
CATEGORY_NAME,
PERSON_ID,
PERSON_FIRST_NAME,
PERSON_SECOND_NAME,
LOCATION_ID,
LOCATION_LATITUDE,
LOCATION_LONGITUDE
)
as
select
	a.TIC_N_TICKET_ID,a.TIC_S_TEXT,a.TIC_D_CREATION_DATE,a.TIC_D_UPDATE_DATE,
	a.TST_N_STATUS_ID,b.TST_S_NAME,
	a.USR_N_USER_ID,c.USR_S_NAME,
	a.TCA_N_CATEGORY_ID,d.TCA_S_NAME,
	a.PER_N_PERSON_ID,e.PER_S_FIRST_NAME,e.PER_S_SECOND_NAME,
	a.LOC_N_LOCATION_ID,f.LOC_D_LAT,f.LOC_D_LNG
	from BSST_TIC_TICKET a
	left join BSST_TST_TICKET_STATUS b on a.TST_N_STATUS_ID=b.TST_N_STATUS_ID
	left join BSST_USR_USER c on c.USR_N_USER_ID=a.USR_N_USER_ID
	left join BSST_TCA_TICKET_CATEGORY d on d.TCA_N_CATEGORY_ID=a.TCA_N_CATEGORY_ID
	left join BSST_PER_PERSON e on e.PER_N_PERSON_ID=a.PER_N_PERSON_ID
	left join BSST_LOC_LOCATION f on f.LOC_N_LOCATION_ID=a.LOC_N_LOCATION_ID;
