delete from BSST_TWF_TICKET_WORKFLOW;
delete from BSST_TST_TICKET_STATUS;		

ALTER TABLE BSST_TST_TICKET_STATUS AUTO_INCREMENT= 1;

INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Candidate','Candidate');
INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Open','Open');
INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Resolved','Resolved');
INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Rejected','Rejected');
	
ALTER TABLE BSST_TCA_TICKET_CATEGORY AUTO_INCREMENT= 1;	


insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Candidate'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'));
			
insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Candidate'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Rejected'));

insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Resolved'));

insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Rejected'));
			
insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Rejected'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'));
			