delete from BSST_TWF_TICKET_WORKFLOW;
delete from BSST_TSL_TICKET_STATUS_LANG;
delete from BSST_TST_TICKET_STATUS;		

ALTER TABLE BSST_TST_TICKET_STATUS AUTO_INCREMENT= 1;

INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Candidate','Candidate');
INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Open','Open');
INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Resolved','Resolved');
INSERT INTO BSST_TST_TICKET_STATUS(TST_S_NAME,TST_S_DESC)
	VALUES ('Rejected','Rejected');
	

delete from BSST_TSL_TICKET_STATUS_LANG;		
	
INSERT INTO BSST_TSL_TICKET_STATUS_LANG(TST_N_STATUS_ID,LAN_N_LANG_ID,TSL_S_NAME,TSL_S_DESC)
VALUES (
(SELECT TST_N_STATUS_ID from BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Candidate'),
(SELECT LAN_N_LANG_ID from BSST_LAN_LANGUAGE WHERE LAN_S_CODE='it'),
'Candidato','Candidato');

INSERT INTO BSST_TSL_TICKET_STATUS_LANG(TST_N_STATUS_ID,LAN_N_LANG_ID,TSL_S_NAME,TSL_S_DESC)
VALUES (
(SELECT TST_N_STATUS_ID from BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'),
(SELECT LAN_N_LANG_ID from BSST_LAN_LANGUAGE WHERE LAN_S_CODE='it'),
'Aperto','Aperto');

INSERT INTO BSST_TSL_TICKET_STATUS_LANG(TST_N_STATUS_ID,LAN_N_LANG_ID,TSL_S_NAME,TSL_S_DESC)
VALUES (
(SELECT TST_N_STATUS_ID from BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Resolved'),
(SELECT LAN_N_LANG_ID from BSST_LAN_LANGUAGE WHERE LAN_S_CODE='it'),
'Risolto','Risolto');

INSERT INTO BSST_TSL_TICKET_STATUS_LANG(TST_N_STATUS_ID,LAN_N_LANG_ID,TSL_S_NAME,TSL_S_DESC)
VALUES (
(SELECT TST_N_STATUS_ID from BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Rejected'),
(SELECT LAN_N_LANG_ID from BSST_LAN_LANGUAGE WHERE LAN_S_CODE='it'),
'Respinto','Respinto');


delete from BSST_TCL_TICKET_CATEGORY_LANG;
delete from BSST_TCA_TICKET_CATEGORY;

ALTER TABLE BSST_TCA_TICKET_CATEGORY AUTO_INCREMENT= 1;	

insert into BSST_TCA_TICKET_CATEGORY(TCA_S_NAME,TCA_S_DESC)
values ('Others','Others');

insert into BSST_TCL_TICKET_CATEGORY_LANG(TCA_N_CATEGORY_ID,LAN_N_LANG_ID,TCL_S_NAME,TCL_S_DESC)
values (
(SELECT TCA_N_CATEGORY_ID from BSST_TCA_TICKET_CATEGORY WHERE TCA_S_NAME='Others'),
(SELECT LAN_N_LANG_ID from BSST_LAN_LANGUAGE WHERE LAN_S_CODE='it'),
'Altro','Altro');


insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Candidate'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'));
			
insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Candidate'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Rejected'));

insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Resolved'));

insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Rejected'));
			
insert into BSST_TWF_TICKET_WORKFLOW(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID)
	values ((select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Rejected'),
			(select TST_N_STATUS_ID FROM BSST_TST_TICKET_STATUS WHERE TST_S_NAME='Open'));
			