delete from BSST_PCA_PRODUCT_CATEGORY;

ALTER TABLE BSST_PCA_PRODUCT_CATEGORY AUTO_INCREMENT= 1;

delete from BSST_PTY_PRODUCT_TYPE;

ALTER TABLE BSST_PTY_PRODUCT_TYPE AUTO_INCREMENT= 1;

insert into BSST_PTY_PRODUCT_TYPE(PTY_S_NAME,PTY_S_DESC)
values ('Product','Product');
insert into BSST_PTY_PRODUCT_TYPE(PTY_S_NAME,PTY_S_DESC)
values ('Service','Service');
insert into BSST_PTY_PRODUCT_TYPE(PTY_S_NAME,PTY_S_DESC)
values ('Resource','Resource');

