DROP TABLE BSST_OPE_OPERATION_GRANT;	
DROP TABLE BSST_BOP_OPERATION_PARAM;
DROP TABLE BSST_BSO_SERVICE_OPERATION;
DROP TABLE BSST_BSV_SERVICE;

CREATE TABLE BSST_BSV_SERVICE (
	BSV_N_SERVICE_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	BSV_S_SERVICE_NAME 	 	VARCHAR(30) NOT NULL,
	BSV_S_SERVICE_URL	 	VARCHAR(50) NOT NULL,
	PRIMARY KEY(BSV_N_SERVICE_ID),
	UNIQUE(BSV_S_SERVICE_NAME)
);

CREATE TABLE BSST_BSO_SERVICE_OPERATION (
	BSO_N_OPERATION_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	BSV_N_SERVICE_ID 		INTEGER UNSIGNED NOT NULL,
	BSO_S_NAME	 			VARCHAR(30) NOT NULL,
	BSO_S_METHOD		 	VARCHAR(30) NOT NULL,	
	BSO_S_OPERATION_URL	 	VARCHAR(50) NOT NULL,
	BSO_S_DESCRIPTION	 	VARCHAR(50),
	PRIMARY KEY(BSO_N_OPERATION_ID),
	CONSTRAINT BSO_S_METHOD_CK CHECK(BSO_S_METHOD IN ('GET','POST')),
	CONSTRAINT BSST_BSO_SERVICE_OPERATION_FK1 FOREIGN KEY(BSV_N_SERVICE_ID) REFERENCES BSST_BSV_SERVICE(BSV_N_SERVICE_ID)
);

CREATE TABLE BSST_BOP_OPERATION_PARAM (
	BOP_PARAM_NAME 			VARCHAR(30) NOT NULL,
	BSO_N_OPERATION_ID 		INTEGER UNSIGNED,
	BOP_C_FLG_URL 			CHAR(1) 	NOT NULL DEFAULT 'N',
	BOP_S_DESCRIPTION	 	VARCHAR(50),
	BOP_C_REQUIRED	 		CHAR(1)		NOT NULL DEFAULT 'N',
	BOP_N_SHOW_ORDER		INTEGER UNSIGNED NOT NULL DEFAULT 1,
	PRIMARY KEY(BOP_PARAM_NAME,BSO_N_OPERATION_ID),
	CONSTRAINT BOP_C_FLG_URL_CK CHECK(BOP_C_FLG_URL IN ('Y','N')),
	CONSTRAINT BOP_C_REQUIRED_CK CHECK(BOP_C_REQUIRED IN ('Y','N')),
	CONSTRAINT BSST_BOP_OPERATION_PARAM_FK1 FOREIGN KEY(BSO_N_OPERATION_ID) REFERENCES BSST_BSO_SERVICE_OPERATION(BSO_N_OPERATION_ID)
);

CREATE TABLE BSST_OPE_OPERATION_GRANT (
	BSO_N_OPERATION_ID 		INTEGER UNSIGNED NOT NULL,
	URO_N_ROLE_ID 			INTEGER UNSIGNED NOT NULL,
	OPE_C_ACTIVE			CHAR(1) DEFAULT 'Y',
	PRIMARY KEY(BSO_N_OPERATION_ID,URO_N_ROLE_ID),
	CONSTRAINT BSST_OPE_OPERATION_GRANT_FK1 FOREIGN KEY(BSO_N_OPERATION_ID) REFERENCES BSST_BSO_SERVICE_OPERATION(BSO_N_OPERATION_ID),
	CONSTRAINT BSST_OPE_OPERATION_GRANT_FK2 FOREIGN KEY(URO_N_ROLE_ID) REFERENCES BSST_URO_ROLE(URO_N_ROLE_ID)
	);
