DROP TABLE BSST_PPR_PRODUCT_REC_PRICE;
DROP TABLE BSST_PRO_PRODUCT;
DROP TABLE BSST_PRL_PRODUCT_LINE;
DROP TABLE BSST_PCA_PRODUCT_CATEGORY;
DROP TABLE BSST_PTY_PRODUCT_TYPE;
DROP TABLE BSST_PRT_REC_PRICE_TYPE;

CREATE TABLE BSST_PCA_PRODUCT_CATEGORY (
	PCA_N_PRODUCT_CATEGORY_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PCA_S_NAME					VARCHAR(30) NOT NULL,
	PCA_N_VAT					DOUBLE NOT NULL,
	PCA_S_DESC					VARCHAR(100),
	UNIQUE(PCA_S_NAME),
	PRIMARY KEY(PCA_N_PRODUCT_CATEGORY_ID)
);

CREATE TABLE BSST_PTY_PRODUCT_TYPE (
	PTY_N_PRODUCT_TYPE_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PTY_S_NAME				VARCHAR(30) NOT NULL,
	PTY_S_DESC				VARCHAR(100),
	UNIQUE(PTY_S_NAME),
	PRIMARY KEY(PTY_N_PRODUCT_TYPE_ID)
);


CREATE TABLE BSST_PRL_PRODUCT_LINE (
	PRL_N_PRODUCT_LINE_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRL_S_NAME					VARCHAR(60) NOT NULL,
	PRL_S_DESC					VARCHAR(500) NOT NULL,
	PRL_N_PRODUCER_ID			INTEGER UNSIGNED,
	PRL_N_DISTRIBUTOR_ID		INTEGER UNSIGNED,
	PCA_N_PRODUCT_CATEGORY_ID 	INTEGER UNSIGNED NOT NULL,
	UNIQUE(PRL_S_NAME),
	PRIMARY KEY(PRL_N_PRODUCT_LINE_ID),
	CONSTRAINT BSST_PRL_PRODUCT_LINE_FK1 FOREIGN KEY(PRL_N_PRODUCER_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PRL_PRODUCT_LINE_FK2 FOREIGN KEY(PRL_N_DISTRIBUTOR_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PRL_PRODUCT_LINE_FK3 FOREIGN KEY(PCA_N_PRODUCT_CATEGORY_ID) 
			REFERENCES BSST_PCA_PRODUCT_CATEGORY(PCA_N_PRODUCT_CATEGORY_ID)
);

CREATE TABLE BSST_PRO_PRODUCT (
	PRO_N_PRODUCT_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRL_N_PRODUCT_LINE_ID 		INTEGER UNSIGNED,
	PRO_S_NAME					VARCHAR(100) NOT NULL,
	PTY_N_PRODUCT_TYPE_ID 		INTEGER UNSIGNED NOT NULL,
	PRO_S_DESC					VARCHAR(800),
	PRO_S_CODE					VARCHAR(64),
	PRO_N_YEAR					VARCHAR(4),
	PRO_N_SIZE_METRIC_ID		INTEGER UNSIGNED,
	PRO_N_SIZE					DOUBLE,
	PRO_N_WIDTH_METRIC_ID		INTEGER UNSIGNED,
	PRO_N_WIDTH					DOUBLE,
	PRO_N_HEIGHT_METRIC_ID		INTEGER UNSIGNED,
	PRO_N_HEIGHT				DOUBLE,
	PRO_N_WEIGHT_METRIC_ID		INTEGER UNSIGNED,
	PRO_N_WEIGHT				DOUBLE,
	PRO_N_QUANTITY_METRIC_ID	INTEGER UNSIGNED,
	PRO_N_QUANTITY				DOUBLE,
	PRO_N_UT_PRICE_CURRENCY_ID	INTEGER UNSIGNED,
	PRO_N_UT_PRICE				DOUBLE,
	PRIMARY KEY(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_PRO_PRODUCT_FK1 FOREIGN KEY(PRL_N_PRODUCT_LINE_ID) 
			REFERENCES BSST_PRL_PRODUCT_LINE(PRL_N_PRODUCT_LINE_ID),
	CONSTRAINT BSST_PRO_PRODUCT_FK2 FOREIGN KEY(PRO_N_SIZE_METRIC_ID) 
			REFERENCES BSST_MET_METRIC(MET_N_METRIC_ID),
	CONSTRAINT BSST_PRO_PRODUCT_FK3 FOREIGN KEY(PRO_N_WIDTH_METRIC_ID) 
			REFERENCES BSST_MET_METRIC(MET_N_METRIC_ID),
	CONSTRAINT BSST_PRO_PRODUCT_FK4 FOREIGN KEY(PRO_N_HEIGHT_METRIC_ID) 
			REFERENCES BSST_MET_METRIC(MET_N_METRIC_ID),
	CONSTRAINT BSST_PRO_PRODUCT_FK5 FOREIGN KEY(PRO_N_WEIGHT_METRIC_ID) 
			REFERENCES BSST_MET_METRIC(MET_N_METRIC_ID),
	CONSTRAINT BSST_PRO_PRODUCT_FK6 FOREIGN KEY(PRO_N_QUANTITY_METRIC_ID) 
			REFERENCES BSST_MET_METRIC(MET_N_METRIC_ID),			
	CONSTRAINT BSST_PRO_PRODUCT_FK7 FOREIGN KEY(PTY_N_PRODUCT_TYPE_ID) 
			REFERENCES BSST_PTY_PRODUCT_TYPE(PTY_N_PRODUCT_TYPE_ID),
	CONSTRAINT BSST_PRP_PRODUCT_FK8 FOREIGN KEY(PRO_N_UT_PRICE_CURRENCY_ID) 
			REFERENCES BSST_CUR_CURRENCY(CUR_N_CURRENCY_ID)
);

CREATE TABLE BSST_PRT_REC_PRICE_TYPE (
	PRT_N_REC_PRICE_TYPE_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRT_S_NAME					VARCHAR(30) NOT NULL,
	PRT_S_DESC					VARCHAR(100),
	UNIQUE(PRT_S_NAME),
	PRIMARY KEY(PRT_N_REC_PRICE_TYPE_ID)
);


CREATE TABLE BSST_PPR_PRODUCT_REC_PRICE (
	PPR_N_PRODUCT_REC_PRICE_ID	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRO_N_PRODUCT_ID 			INTEGER UNSIGNED NOT NULL,
	PPR_D_DATE_START			DATE NOT NULL,
	PPR_D_DATE_END				DATE,
	PRT_N_REC_PRICE_TYPE_ID		INTEGER UNSIGNED NOT NULL,
	PPR_N_REC_PRICE_CURRENCY_ID	INTEGER UNSIGNED,
	PPR_N_REC_PRICE				DOUBLE,
	PPR_N_REC					INTEGER UNSIGNED,
	PRIMARY KEY(PPR_N_PRODUCT_REC_PRICE_ID),
	CONSTRAINT BSST_PPR_PRODUCT_REC_PRICE_FK1 FOREIGN KEY(PRO_N_PRODUCT_ID) 
			REFERENCES BSST_PRO_PRODUCT(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_PPR_PRODUCT_REC_PRICE_FK2 FOREIGN KEY(PRT_N_REC_PRICE_TYPE_ID) 
			REFERENCES BSST_PRT_REC_PRICE_TYPE(PRT_N_REC_PRICE_TYPE_ID),
	CONSTRAINT BSST_PPR_PRODUCT_REC_PRICE_FK3 FOREIGN KEY(PPR_N_REC) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_PPR_PRODUCT_REC_PRICE_FK4 FOREIGN KEY(PPR_N_REC_PRICE_CURRENCY_ID) 
			REFERENCES BSST_CUR_CURRENCY(CUR_N_CURRENCY_ID)		
);


