
DROP TABLE BSST_COM_COMPANY;
CREATE TABLE BSST_COM_COMPANY (
	COM_N_COMPANY_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	COM_S_CODE				VARCHAR(10) NOT NULL,
	COM_S_NAME				VARCHAR(80) NOT NULL,
	COM_S_ADDRESS			VARCHAR(60),
	CIT_N_CITY_ID			INTEGER UNSIGNED,
	COM_S_FISCAL_CODE		VARCHAR(30),
	COM_S_VAT_CODE			VARCHAR(30),
	UNIQUE(COM_S_CODE),
	PRIMARY KEY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_COM_COMPANY_FK1 FOREIGN KEY(CIT_N_CITY_ID) REFERENCES BSST_CIT_CITY(CIT_N_CITY_ID)
);
