DROP TABLE BSST_TTR_TICKET_TRACE;

DROP TABLE BSST_TIC_TICKET;

DROP TABLE BSST_TCL_TICKET_CATEGORY_LANG;
DROP TABLE BSST_TCA_TICKET_CATEGORY;




CREATE TABLE BSST_TCA_TICKET_CATEGORY (
	TCA_N_CATEGORY_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	TCA_S_NAME				VARCHAR(30) NOT NULL,
	TCA_S_DESC				VARCHAR(80),
	UNIQUE(TCA_S_NAME),
	PRIMARY KEY(TCA_N_CATEGORY_ID)
);


CREATE TABLE BSST_TCL_TICKET_CATEGORY_LANG (
	TCA_N_CATEGORY_ID 		INTEGER UNSIGNED NOT NULL,
	LAN_N_LANG_ID 			INTEGER UNSIGNED NOT NULL,
	TCL_S_NAME				VARCHAR(30) NOT NULL,
	TCL_S_DESC				VARCHAR(80),
	UNIQUE(TCL_S_NAME),
	PRIMARY KEY(TCA_N_CATEGORY_ID,LAN_N_LANG_ID),
	CONSTRAINT BSST_TCL_TICKET_CATEGORY_LANG_FK1 FOREIGN KEY(TCA_N_CATEGORY_ID) REFERENCES BSST_TCA_TICKET_CATEGORY(TCA_N_CATEGORY_ID),
	CONSTRAINT BSST_TCL_TICKET_CATEGORY_LANG_FK2 FOREIGN KEY(LAN_N_LANG_ID) REFERENCES BSST_LAN_LANGUAGE(LAN_N_LANG_ID)
);



DROP TABLE BSST_TWF_TICKET_WORKFLOW;
DROP TABLE BSST_TSL_TICKET_STATUS_LANG;
DROP TABLE BSST_TST_TICKET_STATUS;

CREATE TABLE BSST_TST_TICKET_STATUS (
	TST_N_STATUS_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	TST_S_NAME				VARCHAR(30) NOT NULL,
	TST_S_DESC				VARCHAR(80),
	UNIQUE(TST_S_NAME),
	PRIMARY KEY(TST_N_STATUS_ID)
);

CREATE TABLE BSST_TSL_TICKET_STATUS_LANG (
	TST_N_STATUS_ID 		INTEGER UNSIGNED NOT NULL,
	LAN_N_LANG_ID 			INTEGER UNSIGNED NOT NULL,
	TSL_S_NAME				VARCHAR(30) NOT NULL,
	TSL_S_DESC				VARCHAR(80),
	UNIQUE(TSL_S_NAME),
	PRIMARY KEY(TST_N_STATUS_ID,LAN_N_LANG_ID),
	CONSTRAINT BSST_TSL_TICKET_STATUS_LANG_FK1 FOREIGN KEY(TST_N_STATUS_ID) REFERENCES BSST_TST_TICKET_STATUS(TST_N_STATUS_ID),
	CONSTRAINT BSST_TSL_TICKET_STATUS_LANG_FK2 FOREIGN KEY(LAN_N_LANG_ID) REFERENCES BSST_LAN_LANGUAGE(LAN_N_LANG_ID)
);

CREATE TABLE BSST_TWF_TICKET_WORKFLOW (
	TWF_N_START_STATUS_ID 	INTEGER UNSIGNED NOT NULL,
	TWF_N_END_STATUS_ID 	INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID),
	CONSTRAINT BSST_TWF_TICKET_WORKFLOW_FK1 FOREIGN KEY(TWF_N_START_STATUS_ID) 
		REFERENCES BSST_TST_TICKET_STATUS(TST_N_STATUS_ID),
	CONSTRAINT BSST_TWF_TICKET_WORKFLOW_FK2 FOREIGN KEY(TWF_N_END_STATUS_ID) 
		REFERENCES BSST_TST_TICKET_STATUS(TST_N_STATUS_ID)
);


CREATE TABLE BSST_TIC_TICKET (
	TIC_N_TICKET_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	TIC_S_TEXT				VARCHAR(500) NOT NULL,
	TIC_D_CREATION_DATE		DATETIME NOT NULL,
	TIC_D_UPDATE_DATE		DATETIME NOT NULL default now() on update now(),	
	TST_N_STATUS_ID			INTEGER UNSIGNED NOT NULL DEFAULT 1,
	USR_N_USER_ID			INTEGER UNSIGNED NOT NULL,
	TCA_N_CATEGORY_ID		INTEGER UNSIGNED,
	PER_N_PERSON_ID			INTEGER UNSIGNED,
	LOC_N_LOCATION_ID		INTEGER UNSIGNED,
	PRIMARY KEY(TIC_N_TICKET_ID),
	CONSTRAINT BSST_TIC_TICKET_FK1 FOREIGN KEY(TST_N_STATUS_ID) 
		REFERENCES BSST_TST_TICKET_STATUS(TST_N_STATUS_ID),
	CONSTRAINT BSST_TIC_TICKET_FK2 FOREIGN KEY(USR_N_USER_ID) 
		REFERENCES BSST_USR_USER(USR_N_USER_ID),
	CONSTRAINT BSST_TIC_TICKET_FK3 FOREIGN KEY(PER_N_PERSON_ID) 
		REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID),
	CONSTRAINT BSST_TIC_TICKET_FK4 FOREIGN KEY(LOC_N_LOCATION_ID) 
		REFERENCES BSST_LOC_LOCATION(LOC_N_LOCATION_ID),
	CONSTRAINT BSST_TIC_TICKET_FK5 FOREIGN KEY(TCA_N_CATEGORY_ID) 
		REFERENCES BSST_TCA_TICKET_CATEGORY(TCA_N_CATEGORY_ID)
);

CREATE TABLE BSST_TTR_TICKET_TRACE(
	TIC_N_TICKET_ID 		INTEGER UNSIGNED NOT NULL,
	TWF_N_START_STATUS_ID 	INTEGER UNSIGNED NOT NULL,
	TWF_N_END_STATUS_ID 	INTEGER UNSIGNED NOT NULL,
	TTR_D_TRANS_DATE		TIMESTAMP NOT NULL,
	USR_N_USER_ID			INTEGER UNSIGNED NOT NULL,
	TTR_S_NOTE				VARCHAR(200),
	PRIMARY KEY(TIC_N_TICKET_ID,TWF_N_START_STATUS_ID,TWF_N_END_STATUS_ID,TTR_D_TRANS_DATE),
	CONSTRAINT BSST_TTR_TICKET_TRACE_FK1 FOREIGN KEY(USR_N_USER_ID) 
		REFERENCES BSST_USR_USER(USR_N_USER_ID),
	CONSTRAINT BSST_TTR_TICKET_TRACE_FK2 FOREIGN KEY(TIC_N_TICKET_ID) 
		REFERENCES BSST_TIC_TICKET(TIC_N_TICKET_ID)
);
