DROP TABLE BSST_UAP_USER_APP;
DROP TABLE BSST_AME_APP_MESSAGE;	
DROP TABLE BSST_APA_APP_PARAM;
DROP TABLE BSST_AVA_APP_VAR;
DROP TABLE BSST_APP_APP;

CREATE TABLE BSST_APP_APP(
	APP_N_APP_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	APP_S_NAME				VARCHAR(20) NOT NULL,
	APP_S_DESC				VARCHAR(50),
	UNIQUE(APP_S_NAME),
	PRIMARY KEY(APP_N_APP_ID)
);


CREATE TABLE BSST_APA_APP_PARAM (
	APP_N_APP_ID 			INTEGER UNSIGNED NOT NULL,
	APA_S_NAME				VARCHAR(50) NOT NULL,
	APA_S_VALUE				VARCHAR(250) NOT NULL,
	APA_C_TYPE				CHAR(1) NOT NULL,
	PRIMARY KEY(APP_N_APP_ID,APA_S_NAME),
	CONSTRAINT BSST_APA_APP_PARAM_CK CHECK(APA_C_TYPE IN ('I','S','R')),
	CONSTRAINT BSST_APA_APP_PARAM_FK1 FOREIGN KEY(APP_N_APP_ID) REFERENCES BSST_APP_APP(APP_N_APP_ID)
);

CREATE TABLE BSST_AVA_APP_VAR (
	APP_N_APP_ID 			INTEGER UNSIGNED NOT NULL,
	ARV_S_NAME				VARCHAR(50) NOT NULL,
	ARV_S_VALUE				VARCHAR(250) NOT NULL,
	ARV_C_TYPE				CHAR(1) NOT NULL,
	PRIMARY KEY(APP_N_APP_ID,ARV_S_NAME),
	CONSTRAINT BSST_AVA_APP_VAR_CK CHECK(ARV_C_TYPE IN ('I','S','R')),
	CONSTRAINT BSST_AVA_APP_VAR_FK1 FOREIGN KEY(APP_N_APP_ID) REFERENCES BSST_APP_APP(APP_N_APP_ID)
);

CREATE TABLE BSST_AME_APP_MESSAGE (
	APP_N_APP_ID 			INTEGER UNSIGNED NOT NULL,
	LAN_N_LANG_ID 			INTEGER UNSIGNED NOT NULL,
	AME_S_ID				VARCHAR(50) NOT NULL,
	AME_S_VALUE				VARCHAR(1000) NOT NULL,
	PRIMARY KEY(APP_N_APP_ID,LAN_N_LANG_ID,AME_S_ID),
	CONSTRAINT BSST_AME_APP_MESSAGE_FK1 FOREIGN KEY(APP_N_APP_ID) REFERENCES BSST_APP_APP(APP_N_APP_ID),
	CONSTRAINT BSST_AME_APP_MESSAGE_FK2 FOREIGN KEY(LAN_N_LANG_ID) REFERENCES BSST_LAN_LANGUAGE(LAN_N_LANG_ID)
);




