DROP TABLE BSST_FIL_FILE;

CREATE TABLE BSST_FIL_FILE (
	FILE_N_FILE_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	FILE_S_NAME				VARCHAR(30) NOT NULL,
	FILE_N_SIZE				INTEGER UNSIGNED NOT NULL,
	FILE_S_CONTENT_TYPE		VARCHAR(60) NOT NULL,
	FILE_B_CONTENT			LONGBLOB NOT NULL,
	FILE_S_TYPE				VARCHAR(30),
	FILE_S_ENTITY_NAME		VARCHAR(20),
	FILE_N_ENTITY_ID		INTEGER UNSIGNED,
	FILE_S_NOTE				VARCHAR(500),
	PRIMARY KEY(FILE_N_FILE_ID),
	CONSTRAINT BSST_FIL_FILE_CK CHECK(FILE_S_ENTITY_NAME IN ('Person','Company','Location','Ticket'))
);
