DROP TABLE BSST_CON_CONTACT;
DROP TABLE BSST_CTY_CONTACT_TYPE;

CREATE TABLE BSST_CTY_CONTACT_TYPE (
	CTY_N_TYPE_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	CTY_S_NAME				VARCHAR(30) NOT NULL,
	CTY_S_DESC				VARCHAR(80),
	CTY_S_TYPE				VARCHAR(30),
	UNIQUE(CTY_S_NAME),
	PRIMARY KEY(CTY_N_TYPE_ID)
);

CREATE TABLE BSST_CON_CONTACT (
	CON_N_CONTACT_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	CON_S_CONTACT		VARCHAR(300) NOT NULL,
	CON_S_ENTITY_NAME	VARCHAR(20) NOT NULL,
	CON_N_ENTITY_ID		INTEGER UNSIGNED NOT NULL,
	CTY_N_TYPE_ID 		INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(CON_N_CONTACT_ID),
	CONSTRAINT BSST_CON_CONTACT_FK1 FOREIGN KEY(CON_N_CONTACT_ID) REFERENCES BSST_CTY_CONTACT_TYPE(CTY_N_TYPE_ID),
	CONSTRAINT BSST_CON_CONTACT_CK CHECK(CON_S_ENTITY_NAME IN ('Person','Company','CompanyDept'))
);
