DROP TABLE BSST_SHO_SHOPPING;

CREATE TABLE BSST_SHO_SHOPPING (
	SHO_N_SHOPPING_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRO_N_PRODUCT_ID 			INTEGER UNSIGNED NOT NULL,
	MNC_N_COMPANY_ID			INTEGER UNSIGNED NOT NULL,
	COM_N_COMPANY_ID 			INTEGER UNSIGNED,
	PER_N_PERSON_ID 			INTEGER UNSIGNED,
	SHO_N_QUANTITY				DOUBLE UNSIGNED NOT NULL,
	MES_N_METRIC_SCALE_ID   	INTEGER UNSIGNED NOT NULL,
	SHO_N_PRICE					DOUBLE UNSIGNED NOT NULL,
	SHO_N_AMOUNT				DOUBLE UNSIGNED NOT NULL,
	CUR_N_CURRENCY_ID			INTEGER UNSIGNED NOT NULL,
	SHO_D_DATE					DATE NOT NULL,
	SHO_D_DATE_START			DATE,
	SHO_D_DATE_END				DATE,
	PRC_N_PRICE_COMPONENT_ID 	INTEGER UNSIGNED,
	SHO_N_REC_PERIOD			INTEGER UNSIGNED,
	PRIMARY KEY(SHO_N_SHOPPING_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK1 FOREIGN KEY(PRO_N_PRODUCT_ID) 
			REFERENCES BSST_PRO_PRODUCT(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK2 FOREIGN KEY(MES_N_METRIC_SCALE_ID) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK3 FOREIGN KEY(CUR_N_CURRENCY_ID) 
			REFERENCES BSST_CUR_CURRENCY(CUR_N_CURRENCY_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK4 FOREIGN KEY(COM_N_COMPANY_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK5 FOREIGN KEY(PER_N_PERSON_ID) 
			REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK6 FOREIGN KEY(PRC_N_PRICE_COMPONENT_ID) 
			REFERENCES BSST_PRC_PRICE_COMPONENT(PRC_N_PRICE_COMPONENT_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK7 FOREIGN KEY(SHO_N_REC_PERIOD) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_SHO_SHOPPING_FK8 FOREIGN KEY(MNC_N_COMPANY_ID) 
			REFERENCES BSST_MNC_MANAGED_COMPANY(MNC_N_COMPANY_ID)
	
);
