DROP TABLE BSST_PRO_PRODUCT;
DROP TABLE BSST_MET_METRIC;
DROP TABLE BSST_MES_METRIC_SCALE;
DROP TABLE BSST_CUR_CURRENCY;

CREATE TABLE BSST_MET_METRIC (
	MET_N_METRIC_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	MET_S_NAME			VARCHAR(30) NOT NULL,
	UNIQUE(MET_S_NAME),
	PRIMARY KEY(MET_N_METRIC_ID)
);
	
CREATE TABLE BSST_MES_METRIC_SCALE (
	MES_N_METRIC_SCALE_ID	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,	
	MET_N_METRIC_ID 		INTEGER UNSIGNED NOT NULL,
	MES_S_NAME				VARCHAR(30) NOT NULL,
	MES_S_SIMBOL			VARCHAR(15) NOT NULL,
	MES_N_FACTOR			DOUBLE NOT NULL,	
	PRIMARY KEY(MES_N_METRIC_SCALE_ID)
);

CREATE TABLE BSST_CUR_CURRENCY (
	CUR_N_CURRENCY_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	CUR_S_CODE			VARCHAR(10) NOT NULL,
	CUR_S_NAME			VARCHAR(30) NOT NULL,
	UNIQUE(CUR_S_NAME),
	PRIMARY KEY(CUR_N_CURRENCY_ID)
);




