DROP TABLE BSST_PTY_PROPERTY;

CREATE TABLE BSST_PTY_PROPERTY (
	PTY_N_PROPERY_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PTY_S_NAME			VARCHAR(30) NOT NULL,
	PTY_S_VALUE			VARCHAR(250) NOT NULL,
	PTY_S_TYPE			CHAR(1) NOT NULL DEFAULT 'S',
	PTY_S_ENTITY_NAME	VARCHAR(20) NOT NULL,
	PTY_N_ENTITY_ID		INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(PTY_N_PROPERY_ID),
	CONSTRAINT BSST_PTY_PROPERY_CK1 CHECK(PTY_S_ENTITY_NAME IN ('Person','Company','Location','Ticket')),
	CONSTRAINT BSST_PTY_PROPERY_CK2 CHECK(PTY_S_TYPE IN ('S','N'))
);
