DROP TABLE BSST_PRS_PRODUCT_SALE;
DROP TABLE BSST_PSS_PRODUCT_SALE_STATUS;
DROP TABLE BSST_PRO_PRODUCT;
DROP TABLE BSST_PRL_PRODUCT_LINE;
DROP TABLE BSST_PCA_PRODUCT_CATEGORY;

CREATE TABLE BSST_PCA_PRODUCT_CATEGORY (
	PCA_N_PRODUCT_CATEGORY_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PCA_S_NAME					VARCHAR(30) NOT NULL,
	PCA_N_VAT					DOUBLE NOT NULL,
	PCA_S_DESC					VARCHAR(80),
	UNIQUE(PCA_S_NAME),
	PRIMARY KEY(PCA_N_PRODUCT_CATEGORY_ID)
);
	
CREATE TABLE BSST_PRL_PRODUCT_LINE (
	PRL_N_PRODUCT_LINE_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRL_S_NAME					VARCHAR(60) NOT NULL,
	PRL_S_DESC					VARCHAR(500) NOT NULL,
	PRL_N_PRODUCER_ID			INTEGER UNSIGNED,
	PRL_N_DISTRIBUTOR_ID		INTEGER UNSIGNED,
	PCA_N_PRODUCT_CATEGORY_ID 	INTEGER UNSIGNED NOT NULL,
	UNIQUE(PRL_S_NAME),
	PRIMARY KEY(PRL_N_PRODUCT_LINE_ID),
	CONSTRAINT BSST_PRL_PRODUCT_LINE_FK1 FOREIGN KEY(PRL_N_PRODUCER_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PRL_PRODUCT_LINE_FK2 FOREIGN KEY(PRL_N_DISTRIBUTOR_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PRL_PRODUCT_LINE_FK3 FOREIGN KEY(PCA_N_PRODUCT_CATEGORY_ID) 
			REFERENCES BSST_PCA_PRODUCT_CATEGORY(PCA_N_PRODUCT_CATEGORY_ID)
);

CREATE TABLE BSST_PRO_PRODUCT (
	PRO_N_PRODUCT_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRL_N_PRODUCT_LINE_ID 	INTEGER UNSIGNED,
	PRO_S_BARCODE			VARCHAR(64),
	PRO_S_TYPE				VARCHAR(60),
	PRO_S_DESC				VARCHAR(500),
	PRO_N_SIZE				DOUBLE,
	PRO_S_SIZE				VARCHAR(25),
	PRO_N_SIZE_METRIC_ID	INTEGER UNSIGNED,
	PRO_N_WIDTH				DOUBLE,
	PRO_N_WIDTH_METRIC_ID	INTEGER UNSIGNED,
	PRO_N_HEIGHT			DOUBLE,
	PRO_N_HEIGHT_METRIC_ID	INTEGER UNSIGNED,
	PRO_N_WEIGHT			DOUBLE,
	PRO_N_WEIGHT_METRIC_ID	INTEGER UNSIGNED,
	PRO_N_PRICE				DOUBLE,
	PRO_N_PRICE_CURRENCY_ID	INTEGER UNSIGNED,
	PRIMARY KEY(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_PRO_PRODUCT_FK1 FOREIGN KEY(PRL_N_PRODUCT_LINE_ID) 
			REFERENCES BSST_PRL_PRODUCT_LINE(PRL_N_PRODUCT_LINE_ID)
);

CREATE TABLE BSST_PSS_PRODUCT_SALE_STATUS(
	PSS_N_STATUS_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PSS_S_NAME				VARCHAR(30) NOT NULL,
	PSS_S_DESC				VARCHAR(80),
	UNIQUE(PSS_S_NAME),
	PRIMARY KEY(PSS_N_STATUS_ID)
);

CREATE TABLE BSST_PRS_PRODUCT_SALE(
	PRS_N_PRODUCT_SALE_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRO_N_PRODUCT_ID 			INTEGER UNSIGNED NOT NULL,
	PSS_N_STATUS_ID 			INTEGER UNSIGNED NOT NULL,
	COM_N_COMPANY_ID 			INTEGER UNSIGNED NOT NULL,
	PRS_N_PARTNER_ID			INTEGER UNSIGNED,
	PRS_N_CUSTOMER_COMPANY_ID	INTEGER UNSIGNED,
	PRS_N_CUSTOMER_PERSON_ID	INTEGER UNSIGNED,
	PRS_D_DATE					DATE NOT NULL,
	PRS_N_QTY					DOUBLE UNSIGNED NOT NULL,
	PRS_N_QTY_METRIC_ID			INTEGER UNSIGNED NOT NULL,
	PRS_N_PRICE					DOUBLE NOT NULL,
	PRS_N_PRICE_CURRENCY_ID		INTEGER UNSIGNED NOT NULL,
	PRS_N_PRICE_PARTNER			DOUBLE,
	PRIMARY KEY(PRS_N_PRODUCT_SALE_ID),
	CONSTRAINT BSST_PRS_PRODUCT_SALE_FK1 FOREIGN KEY(PRO_N_PRODUCT_ID) 
			REFERENCES BSST_PRO_PRODUCT(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_PRS_PRODUCT_SALE_FK2 FOREIGN KEY(PSS_N_STATUS_ID) 
			REFERENCES BSST_PSS_PRODUCT_SALE_STATUS(PSS_N_STATUS_ID),
	CONSTRAINT BSST_PRS_PRODUCT_SALE_FK3 FOREIGN KEY(COM_N_COMPANY_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PRS_PRODUCT_SALE_FK4 FOREIGN KEY(PRS_N_PARTNER_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PRS_PRODUCT_SALE_FK5 FOREIGN KEY(PRS_N_CUSTOMER_COMPANY_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PRS_PRODUCT_SALE_FK6 FOREIGN KEY(PRS_N_CUSTOMER_PERSON_ID) 
			REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID)		

);

