DROP TABLE BSST_TCL_TICKET_CATEGORY_LANG;
DROP TABLE BSST_TSL_TICKET_STATUS_LANG;
DROP TABLE BSST_TTR_TICKET_TRACE;
DROP TABLE BSST_TIC_TICKET;
DROP TABLE BSST_UAP_USER_APP;
DROP TABLE BSST_LLA_LOCATION_LANG;
DROP TABLE BSST_LOC_LOCATION;

DROP TABLE BSST_OPE_OPERATION_GRANT;	
DROP TABLE BSST_USE_USER_SESSION;
DROP TABLE BSST_USR_USER;
DROP TABLE BSST_URO_ROLE;


CREATE TABLE BSST_URO_ROLE (
	URO_N_ROLE_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	URO_S_NAME	 			VARCHAR(30) NOT NULL,
	URO_S_DESCRIPTION		VARCHAR(60),
	URO_N_PARENT_ROLE_ID 	INTEGER UNSIGNED,
	PRIMARY KEY(URO_N_ROLE_ID),
	UNIQUE(URO_S_NAME),
	CONSTRAINT BSST_URO_ROLE_FK1 FOREIGN KEY(URO_N_PARENT_ROLE_ID) REFERENCES BSST_URO_ROLE(URO_N_ROLE_ID)
);


CREATE TABLE BSST_USR_USER (
	USR_N_USER_ID	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	USR_S_USER_ID	VARCHAR(50) NOT NULL,
	USR_B_PSW		VARBINARY(60) NOT NULL,
	USR_B_SALT		VARBINARY(60) NOT NULL,
	USR_S_NAME		VARCHAR(50) NOT NULL,
	URO_N_ROLE_ID	INTEGER UNSIGNED NOT NULL,
	LAN_N_LANG_ID	INTEGER UNSIGNED NOT NULL,
	USR_C_ACTIVE	CHAR(1) DEFAULT 'Y',
	PER_N_PERSON_ID INTEGER UNSIGNED,
	PRIMARY KEY(USR_N_USER_ID),
	UNIQUE(USR_S_USER_ID),
	CONSTRAINT BSST_USR_USER_FK1 FOREIGN KEY(URO_N_ROLE_ID) REFERENCES BSST_URO_ROLE(URO_N_ROLE_ID),
	CONSTRAINT BSST_USR_USER_FK2 FOREIGN KEY(LAN_N_LANG_ID) REFERENCES BSST_LAN_LANGUAGE(LAN_N_LANG_ID),
	CONSTRAINT BSST_USR_USER_FK3 FOREIGN KEY(PER_N_PERSON_ID) REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID)
);

CREATE TABLE BSST_USE_USER_SESSION (
	USR_N_USER_ID		INTEGER UNSIGNED NOT NULL,
	USE_S_TOKEN			VARCHAR(120) NOT NULL,
	USE_T_CREATE_TIME 	TIMESTAMP NOT NULL,
	USE_T_UPDATE_TIME	TIMESTAMP NOT NULL,
	PRIMARY KEY(USR_N_USER_ID),
	CONSTRAINT BSST_USE_USER_SESSION_FK1 FOREIGN KEY(USR_N_USER_ID) REFERENCES BSST_USR_USER(USR_N_USER_ID)
);


CREATE TABLE BSST_UAP_USER_APP(
	USR_N_USER_ID	INTEGER UNSIGNED NOT NULL,
	APP_N_APP_ID 	INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(USR_N_USER_ID,APP_N_APP_ID),
	CONSTRAINT BSST_UAP_USER_APP_FK1 FOREIGN KEY(USR_N_USER_ID) REFERENCES BSST_USR_USER(USR_N_USER_ID),
	CONSTRAINT BSST_UAP_USER_APP_FK2 FOREIGN KEY(APP_N_APP_ID) REFERENCES BSST_APP_APP(APP_N_APP_ID)
);