DROP TABLE BSST_TTR_TICKET_TRACE;

DROP TABLE BSST_TIC_TICKET;

DROP TABLE BSST_TCL_TICKET_CATEGORY_LANG;
DROP TABLE BSST_TCA_TICKET_CATEGORY;

DROP TABLE BSST_LLA_LOCATION_LANG;
DROP TABLE BSST_LOC_LOCATION;


CREATE TABLE BSST_LOC_LOCATION(
	LOC_N_LOCATION_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	LOC_S_NAME				VARCHAR(50) NOT NULL,
	LOC_D_CREATION_DATE		TIMESTAMP NOT NULL,
	LOC_S_DESC				VARCHAR(2500),
	LOC_S_TYPE				VARCHAR(30),
	LOC_D_LAT 				DOUBLE NOT NULL,  
  	LOC_D_LNG 				DOUBLE NOT NULL,
  	CIT_N_CITY_ID 			INTEGER UNSIGNED,
  	USR_N_USER_ID			INTEGER UNSIGNED NOT NULL,
  	PER_N_PERSON_ID			INTEGER UNSIGNED,
	UNIQUE(LOC_S_NAME),
	PRIMARY KEY(LOC_N_LOCATION_ID),
	CONSTRAINT BSST_LOC_LOCATION_FK1 FOREIGN KEY(CIT_N_CITY_ID) REFERENCES BSST_CIT_CITY(CIT_N_CITY_ID),
	CONSTRAINT BSST_LOC_LOCATION_FK2 FOREIGN KEY(USR_N_USER_ID) REFERENCES BSST_USR_USER(USR_N_USER_ID),
	CONSTRAINT BSST_LOC_LOCATION_FK3 FOREIGN KEY(PER_N_PERSON_ID) REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID)
);


CREATE TABLE BSST_LLA_LOCATION_LANG(
	LOC_N_LOCATION_ID 		INTEGER UNSIGNED NOT NULL,
	LAN_N_LANG_ID 			INTEGER UNSIGNED NOT NULL,
	LLA_S_NAME				VARCHAR(50) NOT NULL,
	LLA_S_DESC				VARCHAR(2500) NOT NULL,
	PRIMARY KEY(LOC_N_LOCATION_ID,LAN_N_LANG_ID),
	CONSTRAINT BSST_LLA_LOCATION_LANG_FK1 FOREIGN KEY(LAN_N_LANG_ID) REFERENCES BSST_LAN_LANGUAGE(LAN_N_LANG_ID)
);
