DROP TABLE BSST_CPE_COMPANY_PERS;
DROP TABLE BSST_CDE_COMPANY_DEPT;
DROP TABLE BSST_CGR_COMPANY_GROUP;
DROP TABLE BSST_COM_COMPANY;

CREATE TABLE BSST_COM_COMPANY (
	COM_N_COMPANY_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	COM_S_CODE				VARCHAR(10) NOT NULL,
	COM_S_NAME				VARCHAR(80) NOT NULL,
	COM_S_ADDRESS			VARCHAR(60),
	CIT_N_CITY_ID			INTEGER UNSIGNED,
	COM_S_ZIP				VARCHAR(15),
  	COM_S_FISCAL_CODE		VARCHAR(30),
	COM_S_VAT_CODE			VARCHAR(30),
	UNIQUE(COM_S_CODE),
	PRIMARY KEY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_COM_COMPANY_FK1 FOREIGN KEY(CIT_N_CITY_ID) REFERENCES BSST_CIT_CITY(CIT_N_CITY_ID)
);

CREATE TABLE BSST_CDE_COMPANY_DEPT (
	CDE_N_DEPT_ID			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	COM_N_COMPANY_ID 		INTEGER UNSIGNED NOT NULL,
	CDE_S_CODE				VARCHAR(20) NOT NULL,
	CDE_S_NAME				VARCHAR(80) NOT NULL,
	CDE_S_ADDRESS			VARCHAR(60),
	CIT_N_CITY_ID			INTEGER UNSIGNED,
	CDE_S_ZIP				VARCHAR(15),
	CDE_N_PARENT_DEPT_ID	INTEGER UNSIGNED,
	PRIMARY KEY(CDE_N_DEPT_ID),
	CONSTRAINT BSST_CDE_COMPANY_DEPT_FK1 FOREIGN KEY(CIT_N_CITY_ID) REFERENCES BSST_CIT_CITY(CIT_N_CITY_ID),
	CONSTRAINT BSST_CDE_COMPANY_DEPT_FK2 FOREIGN KEY(COM_N_COMPANY_ID) REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_CDE_COMPANY_DEPT_FK3 FOREIGN KEY(CDE_N_PARENT_DEPT_ID) REFERENCES BSST_CDE_COMPANY_DEPT(CDE_N_DEPT_ID)
);

CREATE TABLE BSST_CGR_COMPANY_GROUP (
	CGR_N_GROUP_ID 		INTEGER UNSIGNED NOT NULL,
	CGR_N_COMPANY_ID	INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(CGR_N_GROUP_ID,CGR_N_COMPANY_ID),
	CONSTRAINT BSST_CGR_COMPANY_GROUP_FK1 FOREIGN KEY(CGR_N_GROUP_ID) REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_CGR_COMPANY_GROUP_FK2 FOREIGN KEY(CGR_N_COMPANY_ID) REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID)
);

DROP TABLE BSST_CRL_COMPANY_PERS_ROLE_LANG;		
DROP TABLE BSST_CRO_COMPANY_PERS_ROLE;

CREATE TABLE BSST_CRO_COMPANY_PERS_ROLE(
	CRO_N_ROLE_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	CRO_S_NAME	 			VARCHAR(30) NOT NULL,
	CRO_S_DESC 		        VARCHAR(60),
	PRIMARY KEY(CRO_N_ROLE_ID),
	UNIQUE(CRO_S_NAME)
);

CREATE TABLE BSST_CRL_COMPANY_PERS_ROLE_LANG(
	CRO_N_ROLE_ID 			INTEGER UNSIGNED,
	LAN_N_LANG_ID 			INTEGER UNSIGNED NOT NULL,
	CRL_S_NAME				VARCHAR(30) NOT NULL,
	CRL_S_DESC				VARCHAR(80),
	UNIQUE(CRL_S_NAME),
	PRIMARY KEY(CRO_N_ROLE_ID,LAN_N_LANG_ID),
	CONSTRAINT BSST_CRL_COMPANY_PERS_ROLE_LANG_FK1 FOREIGN KEY(CRO_N_ROLE_ID) REFERENCES BSST_CRO_COMPANY_PERS_ROLE(CRO_N_ROLE_ID),
	CONSTRAINT BSST_CRL_COMPANY_PERS_ROLE_LANG_FK2 FOREIGN KEY(LAN_N_LANG_ID) REFERENCES BSST_LAN_LANGUAGE(LAN_N_LANG_ID)
);


CREATE TABLE BSST_CPE_COMPANY_PERS(
	PER_N_PERSON_ID 		INTEGER UNSIGNED NOT NULL,
	CRO_N_ROLE_ID 			INTEGER UNSIGNED NOT NULL,
	CDE_N_DEPT_ID			INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(PER_N_PERSON_ID,CDE_N_DEPT_ID),
	CONSTRAINT BSST_CPE_COMPANY_PERS_FK1 FOREIGN KEY(PER_N_PERSON_ID) REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID),
	CONSTRAINT BSST_CPE_COMPANY_PERS_FK2 FOREIGN KEY(CRO_N_ROLE_ID) REFERENCES BSST_CRO_COMPANY_PERS_ROLE(CRO_N_ROLE_ID),
	CONSTRAINT BSST_CPE_COMPANY_PERS_FK3 FOREIGN KEY(CDE_N_DEPT_ID) REFERENCES BSST_CDE_COMPANY_DEPT(CDE_N_DEPT_ID)
);

	


