DROP TABLE BSST_PRI_PRICE;
DROP TABLE BSST_PRP_PRICE_PLAN;
DROP TABLE BSST_PRC_PRICE_COMPONENT;
DROP TABLE BSST_PRT_PRICE_TYPE;

CREATE TABLE BSST_PRT_PRICE_TYPE (
	PRT_N_PRICE_TYPE_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRT_S_CODE 				VARCHAR(20) NOT NULL,
	PRT_S_NAME				VARCHAR(50) NOT NULL,
	PRT_S_DESC				VARCHAR(100),
	UNIQUE(PRT_S_CODE),
	PRIMARY KEY(PRT_N_PRICE_TYPE_ID)
);

CREATE TABLE BSST_PRC_PRICE_COMPONENT (
	PRC_N_PRICE_COMPONENT_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRC_S_CODE 					VARCHAR(20) NOT NULL,
	PRC_S_NAME					VARCHAR(50) NOT NULL,
	PRC_S_DESC					VARCHAR(100),
	PRT_N_PRICE_TYPE_ID 		INTEGER UNSIGNED NOT NULL,
	MET_N_METRIC_ID 			INTEGER UNSIGNED,
	UNIQUE(PRC_S_CODE),
	PRIMARY KEY(PRC_N_PRICE_COMPONENT_ID),
	CONSTRAINT BSST_PRC_PRICE_COMPONENT_FK1 FOREIGN KEY(PRT_N_PRICE_TYPE_ID) 
			REFERENCES BSST_PRT_PRICE_TYPE(PRT_N_PRICE_TYPE_ID),
	CONSTRAINT BSST_PRC_PRICE_COMPONENT_FK2 FOREIGN KEY(MET_N_METRIC_ID) 
			REFERENCES BSST_MET_METRIC(MET_N_METRIC_ID)		
);


CREATE TABLE BSST_PRP_PRICE_PLAN ( 
	PRP_N_PRICE_PLAN_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRO_N_PRODUCT_ID 			INTEGER UNSIGNED NOT NULL,
	PRC_N_PRICE_COMPONENT_ID 	INTEGER UNSIGNED NOT NULL,
	PRP_D_DATE_START			DATE NOT NULL,
	PRP_D_DATE_END				DATE,
	PRIMARY KEY(PRP_N_PRICE_PLAN_ID),
	CONSTRAINT BSST_PRP_PRICE_PLAN_FK1 FOREIGN KEY(PRO_N_PRODUCT_ID) 
			REFERENCES BSST_PRO_PRODUCT(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_PRP_PRICE_PLAN_FK2 FOREIGN KEY(PRC_N_PRICE_COMPONENT_ID) 
			REFERENCES BSST_PRC_PRICE_COMPONENT(PRT_N_PRICE_TYPE_ID)
);

CREATE TABLE BSST_PRI_PRICE (
	PRI_N_PRICE_ID 				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PRP_N_PRICE_PLAN_ID 		INTEGER UNSIGNED NOT NULL,
	MES_N_METRIC_SCALE_ID		INTEGER UNSIGNED,
	PRI_N_QUOTE					REAL UNSIGNED,
	CUR_N_CURRENCY_ID			INTEGER UNSIGNED,
	PRI_N_REC_PERIOD			INTEGER UNSIGNED,
	PRI_D_DATE_START			DATE NOT NULL,
	PRI_D_DATE_END				DATE,
	PRIMARY KEY(PRI_N_PRICE_ID),
	CONSTRAINT BSST_PRI_PRICE_FK1 FOREIGN KEY(PRP_N_PRICE_PLAN_ID) 
			REFERENCES BSST_PRP_PRICE_PLAN(PRP_N_PRICE_PLAN_ID),
	CONSTRAINT BSST_PRI_PRICE_FK2 FOREIGN KEY(MES_N_METRIC_SCALE_ID) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_PRI_PRICE_FK3 FOREIGN KEY(CUR_N_CURRENCY_ID) 
			REFERENCES BSST_CUR_CURRENCY(CUR_N_CURRENCY_ID),
	CONSTRAINT BSST_PRI_PRICE_FK4 FOREIGN KEY(PRI_N_REC_PERIOD) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID)	
);



