DROP TABLE BSST_SIN_SERVICE_INSTANCE;
DROP TABLE BSST_SER_SERVICE;
DROP TABLE BSST_SST_SERVICE_STATUS;
DROP TABLE BSST_SCA_SERVICE_CATEGORY;

CREATE TABLE BSST_SCA_SERVICE_CATEGORY (
	SCA_N_SERVICE_CATEGORY_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SCA_S_NAME					VARCHAR(30) NOT NULL,
	SCA_N_VAT					DOUBLE NOT NULL,
	SCA_S_DESC					VARCHAR(80),
	UNIQUE(SCA_S_NAME),
	PRIMARY KEY(SCA_N_SERVICE_CATEGORY_ID)
);
	
CREATE TABLE BSST_SER_SERVICE (
	SER_N_SERVICE_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SER_S_NAME					VARCHAR(60) NOT NULL,
	SER_S_DESC					VARCHAR(300) NOT NULL,
	SER_S_TYPE					VARCHAR(60),
	SCA_N_SERVICE_CATEGORY_ID 	INTEGER UNSIGNED NOT NULL,
	UNIQUE(SER_S_NAME),
	PRIMARY KEY(SER_N_SERVICE_ID)
);

CREATE TABLE BSST_SST_SERVICE_STATUS(
	SST_N_STATUS_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SST_S_NAME				VARCHAR(30) NOT NULL,
	SST_S_DESC				VARCHAR(80),
	UNIQUE(SST_S_NAME),
	PRIMARY KEY(SST_N_STATUS_ID)
);

CREATE TABLE BSST_SIN_SERVICE_INSTANCE (
	SIN_N_SERVICE_INSTANCE_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SER_N_SERVICE_ID 				INTEGER UNSIGNED NOT NULL,
	SST_N_STATUS_ID 				INTEGER UNSIGNED NOT NULL,
	COM_N_COMPANY_ID 				INTEGER UNSIGNED NOT NULL,
	SIN_N_PARTNER_ID				INTEGER UNSIGNED,
	SIN_N_CUSTOMER_COMPANY_ID		INTEGER UNSIGNED,
	SIN_N_CUSTOMER_PERSON_ID		INTEGER UNSIGNED,
	SIN_D_DATE_START				DATE NOT NULL,
	SIN_D_DATE_END					DATE NOT NULL,
	PRIMARY KEY(SIN_N_SERVICE_INSTANCE_ID),
	CONSTRAINT BSST_SIN_SERVICE_INSTANCE_FK1 FOREIGN KEY(COM_N_COMPANY_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_SIN_SERVICE_INSTANCE_FK2 FOREIGN KEY(SIN_N_PARTNER_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_SIN_SERVICE_INSTANCE_FK3 FOREIGN KEY(SER_N_SERVICE_ID) 
			REFERENCES BSST_SER_SERVICE(SER_N_SERVICE_ID),
	CONSTRAINT BSST_SIN_SERVICE_INSTANCE_FK4 FOREIGN KEY(SST_N_STATUS_ID) 
			REFERENCES BSST_SST_SERVICE_STATUS(SST_N_STATUS_ID),
	CONSTRAINT BSST_SIN_SERVICE_INSTANCE_FK5 FOREIGN KEY(SIN_N_CUSTOMER_COMPANY_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_SIN_SERVICE_INSTANCE_FK6 FOREIGN KEY(SIN_N_CUSTOMER_PERSON_ID) 
			REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID)
);










