DROP TABLE BSST_ATT_ATTRIBUTE;

CREATE TABLE BSST_ATT_ATTRIBUTE (
	ATT_N_ATTRIBUTE_ID 	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	ATT_S_NAME			VARCHAR(30) NOT NULL,
	ATT_S_VALUE			VARCHAR(250) NOT NULL,
	ATT_S_TYPE			CHAR(1) NOT NULL DEFAULT 'S',
	ATT_S_ENTITY_NAME	VARCHAR(20) NOT NULL,
	ATT_N_ENTITY_ID		INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(ATT_N_ATTRIBUTE_ID),
	CONSTRAINT BSST_ATT_ATTRIBUTE_CK1 CHECK(ATT_S_ENTITY_NAME IN ('Person','Company','Location','Ticket')),
	CONSTRAINT BSST_ATT_ATTRIBUTE_CK2 CHECK(ATT_S_TYPE IN ('S','N'))
);
