DROP TABLE BSST_USE_USER_SESSION;
DROP TABLE BSST_TCL_TICKET_CATEGORY_LANG;
DROP TABLE BSST_TSL_TICKET_STATUS_LANG;
DROP TABLE BSST_TTR_TICKET_TRACE;
DROP TABLE BSST_TIC_TICKET;
DROP TABLE BSST_UAP_USER_APP;
DROP TABLE BSST_LLA_LOCATION_LANG;
DROP TABLE BSST_LOC_LOCATION;
DROP TABLE BSST_USR_USER;

DROP TABLE BSST_PER_PERSON;
CREATE TABLE BSST_PER_PERSON (
	PER_N_PERSON_ID 		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PER_S_CODE				VARCHAR(50) NOT NULL,
	PER_S_FIRST_NAME		VARCHAR(50) NOT NULL,
	PER_S_SECOND_NAME		VARCHAR(50) NOT NULL,
	PER_C_GENDER			CHAR(1),
	PER_S_ADDRESS			VARCHAR(60),
	CIT_N_CITY_ID			INTEGER UNSIGNED,
	PER_S_FISCAL_CODE		VARCHAR(30),
	PER_D_BIRTH_DAY			DATE,
	CIT_N_BIRTH_CITY_ID		INTEGER UNSIGNED,
	UNIQUE(PER_S_CODE),
	PRIMARY KEY(PER_N_PERSON_ID),
	CONSTRAINT BSST_PER_PERSON_FK1 FOREIGN KEY(CIT_N_CITY_ID) REFERENCES BSST_CIT_CITY(CIT_N_CITY_ID),
	CONSTRAINT BSST_PER_PERSON_FK2 FOREIGN KEY(CIT_N_BIRTH_CITY_ID) REFERENCES BSST_CIT_CITY(CIT_N_CITY_ID),
	CONSTRAINT BSST_PER_PERSON_CK CHECK(PER_C_GENDER IN ('M','F'))
);
