CREATE TABLE BSST_SAL_SALE (
	SAL_N_SALE_ID 				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	MNC_N_COMPANY_ID			INTEGER UNSIGNED NOT NULL,
	PRO_N_PRODUCT_ID 			INTEGER UNSIGNED NOT NULL,
	COM_N_COMPANY_ID 			INTEGER UNSIGNED,
	PER_N_PERSON_ID 			INTEGER UNSIGNED,
	SAL_N_QUANTITY				DOUBLE UNSIGNED,
	MES_N_METRIC_SCALE_ID   	INTEGER UNSIGNED,
	SAL_N_PRICE					DOUBLE NOT NULL,
	SAL_N_AMOUNT				DOUBLE NOT NULL,
	CUR_N_CURRENCY_ID			INTEGER UNSIGNED NOT NULL,
	SAL_N_VAT					DOUBLE UNSIGNED NOT NULL,
	SAL_N_VAT_AMOUNT			DOUBLE NOT NULL,
	SAL_D_DATE_START			DATE,
	SAL_D_DATE_END				DATE,
	SAL_D_DATE_CLOSE			DATE,
	PRC_N_PRICE_COMPONENT_ID 	INTEGER UNSIGNED NOT NULL,
	SAL_N_FREQUENCY				INTEGER UNSIGNED,
	SAL_D_DATE					DATE NOT NULL,
	SAL_D_UPDATE_DATE			TIMESTAMP NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
	SAL_C_TACIT_RENEWAL			CHAR(1) NOT NULL default 'N',
	SAL_C_TYPE					CHAR(1) NOT NULL default 'B',
	SAL_N_NEW_SALE_ID			INTEGER UNSIGNED,
	SAL_N_OLD_SALE_ID			INTEGER UNSIGNED,
	PRIMARY KEY(SAL_N_SALE_ID),
	CONSTRAINT BSST_SAL_SALE_CK1 CHECK(SAL_C_TACIT_RENEWAL IN ('Y','N')),
	CONSTRAINT BSST_SAL_SALE_CK2 CHECK(SAL_C_TYPE IN ('B','H','N')),
	CONSTRAINT BSST_SAL_SALE_FK1 FOREIGN KEY(PRO_N_PRODUCT_ID) 
			REFERENCES BSST_PRO_PRODUCT(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_SAL_SALE_FK2 FOREIGN KEY(MES_N_METRIC_SCALE_ID) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_SAL_SALE_FK3 FOREIGN KEY(CUR_N_CURRENCY_ID) 
			REFERENCES BSST_CUR_CURRENCY(CUR_N_CURRENCY_ID),
	CONSTRAINT BSST_SAL_SALE_FK4 FOREIGN KEY(COM_N_COMPANY_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_SAL_SALE_FK5 FOREIGN KEY(PER_N_PERSON_ID) 
			REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID),
	CONSTRAINT BSST_SAL_SALE_FK6 FOREIGN KEY(PRC_N_PRICE_COMPONENT_ID) 
			REFERENCES BSST_PRC_PRICE_COMPONENT(PRC_N_PRICE_COMPONENT_ID),
	CONSTRAINT BSST_SAL_SALE_FK7 FOREIGN KEY(SAL_N_FREQUENCY) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_SAL_SALE_FK8 FOREIGN KEY(MNC_N_COMPANY_ID) 
			REFERENCES BSST_MNC_MANAGED_COMPANY(MNC_N_COMPANY_ID),
	CONSTRAINT BSST_SAL_SALE_FK9 FOREIGN KEY(SAL_N_NEW_SALE_ID) 
			REFERENCES BSST_SAL_SALE(SAL_N_SALE_ID),
	CONSTRAINT BSST_SAL_SALE_FK10 FOREIGN KEY(SAL_N_OLD_SALE_ID) 
			REFERENCES BSST_SAL_SALE(SAL_N_SALE_ID)		
);



