CREATE TABLE BSST_PUR_PURCHASE (
	PUR_N_PURCHASE_ID 			INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	MNC_N_COMPANY_ID			INTEGER UNSIGNED NOT NULL,
	PRO_N_PRODUCT_ID 			INTEGER UNSIGNED NOT NULL,
	COM_N_COMPANY_ID 			INTEGER UNSIGNED,
	PER_N_PERSON_ID 			INTEGER UNSIGNED,
	PUR_N_QUANTITY				DOUBLE UNSIGNED,
	MES_N_METRIC_SCALE_ID   	INTEGER UNSIGNED,
	PUR_N_PRICE					DOUBLE NOT NULL,
	PUR_N_AMOUNT				DOUBLE NOT NULL,
	CUR_N_CURRENCY_ID			INTEGER UNSIGNED NOT NULL,
	PUR_N_VAT					DOUBLE UNSIGNED NOT NULL,
	PUR_N_VAT_AMOUNT			DOUBLE NOT NULL,
	PUR_D_DATE_START			DATE,
	PUR_D_DATE_END				DATE,
	PUR_D_DATE_CLOSE			DATE,
	PRC_N_PRICE_COMPONENT_ID 	INTEGER UNSIGNED NOT NULL,
	PUR_N_FREQUENCY				INTEGER UNSIGNED,
	PUR_D_DATE					DATE NOT NULL,
	PUR_D_UPDATE_DATE			TIMESTAMP NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
	PUR_C_TACIT_RENEWAL			CHAR(1) NOT NULL default 'N',
	PUR_C_TYPE					CHAR(1) NOT NULL default 'B',
	PUR_N_NEW_PURCHASE_ID		INTEGER UNSIGNED,
	PUR_N_OLD_PURCHASE_ID		INTEGER UNSIGNED,
	PRIMARY KEY(PUR_N_PURCHASE_ID),
	CONSTRAINT BSST_PUR_PURCHASE_CK1 CHECK(PUR_C_TACIT_RENEWAL IN ('Y','N')),
	CONSTRAINT BSST_PUR_PURCHASE_CK2 CHECK(PUR_C_TYPE IN ('B','H','N')),
	CONSTRAINT BSST_PUR_PURCHASE_FK1 FOREIGN KEY(PRO_N_PRODUCT_ID) 
			REFERENCES BSST_PRO_PRODUCT(PRO_N_PRODUCT_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK2 FOREIGN KEY(MES_N_METRIC_SCALE_ID) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK3 FOREIGN KEY(CUR_N_CURRENCY_ID) 
			REFERENCES BSST_CUR_CURRENCY(CUR_N_CURRENCY_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK4 FOREIGN KEY(COM_N_COMPANY_ID) 
			REFERENCES BSST_COM_COMPANY(COM_N_COMPANY_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK5 FOREIGN KEY(PER_N_PERSON_ID) 
			REFERENCES BSST_PER_PERSON(PER_N_PERSON_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK6 FOREIGN KEY(PRC_N_PRICE_COMPONENT_ID) 
			REFERENCES BSST_PRC_PRICE_COMPONENT(PRC_N_PRICE_COMPONENT_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK7 FOREIGN KEY(PUR_N_FREQUENCY) 
			REFERENCES BSST_MES_METRIC_SCALE(MES_N_METRIC_SCALE_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK8 FOREIGN KEY(MNC_N_COMPANY_ID) 
			REFERENCES BSST_MNC_MANAGED_COMPANY(MNC_N_COMPANY_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK9 FOREIGN KEY(PUR_N_NEW_PURCHASE_ID) 
			REFERENCES BSST_PUR_PURCHASE(PUR_N_PURCHASE_ID),
	CONSTRAINT BSST_PUR_PURCHASE_FK10 FOREIGN KEY(PUR_N_OLD_PURCHASE_ID) 
			REFERENCES BSST_PUR_PURCHASE(PUR_N_PURCHASE_ID)		
);
