-- invoice
DROP TABLE BSST_BIR_BILLABLE_REVENUE;
DROP TABLE BSST_BIC_BILLABLE_COST;
DROP TABLE BSST_INV_INVOICE;
DROP TABLE BSST_PIN_PASSIVE_INVOICE;
-- sale
DROP TABLE BSST_SAL_SALE;
-- purchase
DROP TABLE BSST_PUR_PURCHASE;
-- price
DROP TABLE BSST_PRI_PRICE;
DROP TABLE BSST_PRP_PRICE_PLAN;
DROP TABLE BSST_PRC_PRICE_COMPONENT;
DROP TABLE BSST_PRT_PRICE_TYPE;
-- product
DROP TABLE BSST_PRO_PRODUCT;
DROP TABLE BSST_PCA_PRODUCT_CATEGORY;
DROP TABLE BSST_PTY_PRODUCT_TYPE;
-- metric
DROP TABLE BSST_MES_METRIC_SCALE;
DROP TABLE BSST_MET_METRIC;
DROP TABLE BSST_CUR_CURRENCY;
-- object
DROP TABLE BSST_ATV_ATTR_VALUE;
DROP TABLE BSST_ATT_ATTRIBUTE;
DROP TABLE BSST_ATY_ATTR_TYPE;
DROP TABLE BSST_OBJ_OBJECT;
-- contact
DROP TABLE BSST_CON_CONTACT;
DROP TABLE BSST_CTY_CONTACT_TYPE;
-- ticket
DROP TABLE BSST_TTR_TICKET_TRACE;
DROP TABLE BSST_TIC_TICKET;
DROP TABLE BSST_TCL_TICKET_CATEGORY_LANG;
DROP TABLE BSST_TCA_TICKET_CATEGORY;
DROP TABLE BSST_TWF_TICKET_WORKFLOW;
DROP TABLE BSST_TSL_TICKET_STATUS_LANG;
DROP TABLE BSST_TST_TICKET_STATUS;
-- company
DROP TABLE BSST_CRL_COMPANY_PERS_ROLE_LANG;		
DROP TABLE BSST_CPE_COMPANY_PERS;
DROP TABLE BSST_CRO_COMPANY_PERS_ROLE;
DROP TABLE BSST_MNC_MANAGED_COMPANY;
DROP TABLE BSST_CDE_COMPANY_DEPT;
DROP TABLE BSST_CGR_COMPANY_GROUP;
DROP TABLE BSST_COM_COMPANY;
-- location
DROP TABLE BSST_LLA_LOCATION_LANG;
DROP TABLE BSST_LOC_LOCATION;
-- service
DROP TABLE BSST_OPE_OPERATION_GRANT;	
DROP TABLE BSST_BOP_OPERATION_PARAM;
DROP TABLE BSST_BSO_SERVICE_OPERATION;
DROP TABLE BSST_BSV_SERVICE;
-- user
DROP TABLE BSST_UAP_USER_APP;
DROP TABLE BSST_USE_USER_SESSION;
DROP TABLE BSST_USR_USER;
DROP TABLE BSST_URO_ROLE;
-- file
DROP TABLE BSST_FIL_FILE;
-- app
DROP TABLE BSST_AME_APP_MESSAGE;	
DROP TABLE BSST_APA_APP_PARAM;
DROP TABLE BSST_AVA_APP_VAR;
DROP TABLE BSST_APP_APP;
-- person
DROP TABLE BSST_PER_PERSON;
-- geo
DROP TABLE BSST_CIT_CITY;
DROP TABLE BSST_GRE_GEO_REGION_COUNTRY;
DROP TABLE BSST_GRE_GEO_REGION;
DROP TABLE BSST_CON_COUNTRY;
DROP TABLE BSST_LAN_LANGUAGE;





